// Generated by gencpp from file ans_msgs/Image.msg
// DO NOT EDIT!


#ifndef ANS_MSGS_MESSAGE_IMAGE_H
#define ANS_MSGS_MESSAGE_IMAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace ans_msgs
{
template <class ContainerAllocator>
struct Image_
{
  typedef Image_<ContainerAllocator> Type;

  Image_()
    : frameNum(0)
    , im()  {
    }
  Image_(const ContainerAllocator& _alloc)
    : frameNum(0)
    , im(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _frameNum_type;
  _frameNum_type frameNum;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _im_type;
  _im_type im;




  typedef boost::shared_ptr< ::ans_msgs::Image_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ans_msgs::Image_<ContainerAllocator> const> ConstPtr;

}; // struct Image_

typedef ::ans_msgs::Image_<std::allocator<void> > Image;

typedef boost::shared_ptr< ::ans_msgs::Image > ImagePtr;
typedef boost::shared_ptr< ::ans_msgs::Image const> ImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ans_msgs::Image_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ans_msgs::Image_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ans_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'ans_msgs': ['/home/terence/dev/ANS2017/22. ROS/catkin_ws/src/ans_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ans_msgs::Image_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ans_msgs::Image_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ans_msgs::Image_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ans_msgs::Image_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ans_msgs::Image_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ans_msgs::Image_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ans_msgs::Image_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ccb20b8dbeb0b1f07dc0315418d3328";
  }

  static const char* value(const ::ans_msgs::Image_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ccb20b8dbeb0b1fULL;
  static const uint64_t static_value2 = 0x07dc0315418d3328ULL;
};

template<class ContainerAllocator>
struct DataType< ::ans_msgs::Image_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ans_msgs/Image";
  }

  static const char* value(const ::ans_msgs::Image_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ans_msgs::Image_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 frameNum\n\
sensor_msgs/Image im\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ans_msgs::Image_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ans_msgs::Image_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frameNum);
      stream.next(m.im);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Image_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ans_msgs::Image_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ans_msgs::Image_<ContainerAllocator>& v)
  {
    s << indent << "frameNum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.frameNum);
    s << indent << "im: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.im);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANS_MSGS_MESSAGE_IMAGE_H
