set(_CATKIN_CURRENT_PACKAGE "object_tracker")
set(object_tracker_VERSION "0.0.0")
set(object_tracker_MAINTAINER "terence <terence@todo.todo>")
set(object_tracker_PACKAGE_FORMAT "1")
set(object_tracker_BUILD_DEPENDS "message_generation" "cv_bridge" "geometry_msgs" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "tf" "ans_msgs")
set(object_tracker_BUILD_EXPORT_DEPENDS "cv_bridge" "geometry_msgs" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "tf" "message_runtime" "ans_msg")
set(object_tracker_BUILDTOOL_DEPENDS "catkin")
set(object_tracker_BUILDTOOL_EXPORT_DEPENDS )
set(object_tracker_EXEC_DEPENDS "cv_bridge" "geometry_msgs" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "tf" "message_runtime" "ans_msg")
set(object_tracker_RUN_DEPENDS "cv_bridge" "geometry_msgs" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "tf" "message_runtime" "ans_msg")
set(object_tracker_TEST_DEPENDS )
set(object_tracker_DOC_DEPENDS )
set(object_tracker_DEPRECATED "")